### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by GustavoMelloGit** [VaishakVk/react-drag-reorder#6]
I am trying to use it in a React app with Typescript, but it doesn't have types.

**Comment by tan-ahmed** [comment]
Me too. I get this

```
Try `npm i --save-dev @types/react-drag-reorder` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-drag-reorder';
```

**Comment by carlvoller** [comment]
Added typescript support, try installing the latest version of this package and you should have types built-in 👍
